# processing parameters
process_observables: ['jet_ENC_RL', 'jet_pt']

jetR: [0.4]
coneR: [0.4]
jet_pt_thrd_combined: 10.0

debug_level: 0

rm_trk_min_pt: False
do_cs: True
do_ics: False
do_jet_cone: False
do_perpcone: True
do_2cones: True

constituent_subtractor:
  max_distance: 0.25
  alpha: 0
  max_eta: 0.9
  bge_rho_grid_size: 1.0
  max_pt_correct: 100
  ghost_area: 0.01

ics:
  max_distances: [0.25, 0.15]
  alphas: [0.0, 1.0]
  max_eta: 0.9
  jet_median_selector_R: 0.2
  max_pt_correct: 2.8
  ghost_area: 0.0025

# Observable block
jet_ENC_RL:

  common_settings:
    xtitle: '#it{R_{L}}'
    ytitle: '#frac{1}{#it{#sigma}_{jet}} #frac{d#it{#sigma}}{d#it{R_{L}}}'
    pt_bins_reported: [40, 80, 120]
    max_reg_param: 10
    plot_overlay_list:
      - ['config1']

  config1:
    trk_thrd: 1.0
    pt_bins_truth: [5, 20, 40, 60, 80, 120, 150, 200]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120, 150]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120]
    obs_bins_truth: [0., 0.02, 0.04, 0.1, 0.3, 0.6, 0.7, 0.77, 0.83, 0.89, 0.95, 1.0]
    obs_bins_det: [0., 0.02, 0.04, 0.1, 0.3, 0.6, 0.7, 0.77, 0.83, 0.89, 0.95, 1.0]
    obs_bins_det_sys_binning: [0., 0.01, 0.02, 0.03, 0.04, 0.06, 0.12, 0.18, 0.24, 0.3, 0.36, 0.42, 0.48, 0.54, 0.6, 0.66, 0.72, 0.8, 0.9, 0.96, 0.98, 0.99, 1.0]

jet_pt:

  common_settings:
    xtitle: '#it{d_{pair}}'
    ytitle: '#frac{1}{#it{#sigma}_{jet}} #frac{d#it{#sigma}}{d#it{d_{pair}}}'
    pt_bins_reported: [40, 60, 80, 120]
    max_reg_param: 10
    plot_overlay_list:
      - ['config1']
  
  config1:
    trk_thrd: 1.0
    pt_bins_truth: [5, 20, 40, 60, 80, 120, 150, 200]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120, 150]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120]
    obs_bins_truth: [0., 0.02, 0.04, 0.1, 0.3, 0.6, 0.7, 0.77, 0.83, 0.89, 0.95, 1.0]
    obs_bins_det: [0., 0.02, 0.04, 0.1, 0.3, 0.6, 0.7, 0.77, 0.83, 0.89, 0.95, 1.0]
    obs_bins_det_sys_binning: [0., 0.01, 0.02, 0.03, 0.04, 0.06, 0.12, 0.18, 0.24, 0.3, 0.36, 0.42, 0.48, 0.54, 0.6, 0.66, 0.72, 0.8, 0.9, 0.96, 0.98, 0.99, 1.0]
